#!/usr/bin/env python3
"""Bundle the package into one standalone .py file.

Why a bundle at all: the package is the right thing to develop in, but a single
file is the right thing to copy onto a lab machine, a cluster login node, or a
colleague's laptop where you are not going to run a pip install.

Why an embedded importer rather than concatenating modules: concatenation
requires rewriting every relative import, flattening every name, and hoping no
two modules share a symbol. That breaks quietly and is painful to debug. Instead
each module's source is embedded verbatim in a dict and a loader serves them to
the normal import machinery, so relative imports, `__name__`, package structure,
and tracebacks all behave exactly as they do in the installed package.

Usage:
    python scripts/bundle.py [-o dist/deppseek.py]
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
PACKAGE = "deppseek"

PREAMBLE = '''\
#!/usr/bin/env python3
"""DeppSeek {version} -- standalone bundle.

Generated by scripts/bundle.py on {stamp}. Do not edit this file; edit the
package under src/deppseek and re-run the bundler.

Run it directly:
    python deppseek.py --doctor
    python deppseek.py "why does case3 diverge?"

Requires: openai. Optional: rich, prompt_toolkit, pathspec, textual, pint.
"""

import importlib.abc
import importlib.machinery
import importlib.util
import sys
import types

# module name -> (source, is_package)
_BUNDLED_MODULES = {{}}


class _BundleLoader(importlib.abc.InspectLoader):
    """Serves embedded sources to the normal import machinery.

    Implementing InspectLoader rather than rewriting imports means relative
    imports, package __path__, and traceback line numbers all behave as they do
    in the installed package.
    """

    def __init__(self, fullname: str) -> None:
        self.fullname = fullname

    def get_source(self, fullname: str) -> str:
        return _BUNDLED_MODULES[fullname][0]

    def get_filename(self, fullname: str) -> str:
        return f"<bundled {{fullname}}>"

    def is_package(self, fullname: str) -> bool:
        return _BUNDLED_MODULES[fullname][1]

    def create_module(self, spec):
        return None

    def exec_module(self, module: types.ModuleType) -> None:
        source = _BUNDLED_MODULES[module.__name__][0]
        code = compile(source, f"<bundled {{module.__name__}}>", "exec")
        exec(code, module.__dict__)


class _BundleFinder(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _BUNDLED_MODULES:
            return None
        loader = _BundleLoader(fullname)
        spec = importlib.util.spec_from_loader(
            fullname, loader, is_package=_BUNDLED_MODULES[fullname][1]
        )
        if _BUNDLED_MODULES[fullname][1]:
            spec.submodule_search_locations = []
        return spec


'''

POSTAMBLE = '''

# Install the finder ahead of the normal path finders, so a stale copy of the
# package installed elsewhere cannot shadow the bundled one.
sys.meta_path.insert(0, _BundleFinder())

if __name__ == "__main__":
    from deppseek.cli import main

    raise SystemExit(main())
'''


def collect_modules() -> dict[str, tuple[str, bool]]:
    """Map every module in the package to its source and package flag."""
    modules: dict[str, tuple[str, bool]] = {}
    package_root = SRC / PACKAGE

    for path in sorted(package_root.rglob("*.py")):
        relative = path.relative_to(SRC)
        parts = list(relative.with_suffix("").parts)
        is_package = parts[-1] == "__init__"
        if is_package:
            parts = parts[:-1]
        name = ".".join(parts)
        modules[name] = (path.read_text(encoding="utf-8"), is_package)

    return modules


def build(output: Path) -> Path:
    sys.path.insert(0, str(SRC))
    from deppseek import __version__

    modules = collect_modules()
    parts = [
        PREAMBLE.format(
            version=__version__, stamp=time.strftime("%Y-%m-%d %H:%M:%S")
        )
    ]

    for name in sorted(modules):
        source, is_package = modules[name]
        # repr() of the source produces a valid single-line Python literal with
        # every quote, backslash, and newline escaped correctly. Safer than any
        # hand-rolled quoting, and the bundle stays importable.
        parts.append(f"_BUNDLED_MODULES[{name!r}] = ({source!r}, {is_package!r})\n")

    parts.append(POSTAMBLE)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(parts), encoding="utf-8")
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description="Bundle deppseek into one file.")
    parser.add_argument(
        "-o", "--output", default=str(ROOT / "dist" / "deppseek.py"),
        help="output path (default: dist/deppseek.py)",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="import the bundle after building, to verify it works",
    )
    args = parser.parse_args()

    output = build(Path(args.output))
    size = output.stat().st_size
    module_count = len(collect_modules())
    print(f"Wrote {output} ({size:,} bytes, {module_count} modules)")

    if args.check:
        import subprocess

        result = subprocess.run(
            [sys.executable, str(output), "--version"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print("Bundle failed to run:", result.stderr, file=sys.stderr)
            return 1
        print(f"Bundle runs: {result.stdout.strip()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
